name: CI - Checklist de Pull Request

on:
  pull_request:
    branches:
      - beta
      - final

jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica se o checklist foi marcado
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const body = pr.data.body || '';
            const requiredItems = [
              'O código foi testado no ambiente de preview',
              'Supabase (staging) foi atualizado',
              'merge será feito de `beta` para `final`',
              'Todos os testes necessários foram realizados'
            ];
            let missing = requiredItems.filter(item => !body.includes(item));
            if (missing.length > 0) {
              core.setFailed(`Checklist incompleto: ${missing.join(', ')}`);
            } else {
              core.info('Checklist completo.');
            }
