name: Deploy to Staging

on:
  push:
    branches:
      - beta
  pull_request:
    types: [opened, synchronize]
    branches:
      - beta

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Apply Supabase Migrations
        run: |
          npx supabase link --project-ref ${{ secrets.SUPABASE_STAGING_PROJECT_ID }}
          npx supabase db push

      - name: Deploy to Vercel
        if: github.event_name == 'push' && github.ref == 'refs/heads/beta'
        run: |
          npx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          npx vercel build --token=${{ secrets.VERCEL_TOKEN }}
          npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}